# 配置Tomcat
server:
  tomcat:
    # 配置字符集
    uri-encoding: utf-8
    # 配置线程
    threads:
      max: 200 # 最大连接数
      min-spare: 30 # 最小连接数
    # 连接超时时间
    connection-timeout: 5000ms
  # 端口号
  port: 8080
  servlet:
    # 部署路径
    context-path: /emos-wx-api

spring:
  datasource:
    # 类型 阿里巴巴的druid 需要在pom文件中自行添加坐标
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    druid:
      #初始化连接池大小
      initial-size: 8
      #配置最小连接数
      min-idle: 5
      #配置最大连接数
      max-active: 200
      #配置连接等待超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #测试连接
      validation-query: SELECT 1 FROM DUAL
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全
      test-while-idle: true
      #获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      #归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭